openapi: "3.0.0"
info:
  title: "Questions and Answers API"
  version: "1.0.0"
  description: "A simple API for retrieving questions and answers"
servers:
  - url: "https://chatbot-api-one.vercel.app"
    description: "Production server"
paths:
  /scenarios:
    get:
      summary: "Get all scenarios"
      description: "Retrieve a list of all scenarios"
      responses:
        "200":
          description: "A list of scenarios"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    scenarioId: integer
                    question: string
              example:
                - scenarioId: 1
                  question: "I’m dealing with stress and anxiety from my job. I feel really overwhelmed and I dont really know what to do…"

        "500":
          description: "Server Error"
  /scenarios/{id}:
    get:
      summary: "Get a scenario by ID"
      description: "Retrieve a scenario by ID"
      parameters:
        - in: path
          name: id
          schema:
            type: integer
            example: 1
          required: true
          description: "ID of the scenario"
      responses:
        "200":
          description: "Array of questions and answers"
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    Customer: string
                    Zoey: string
              example:
                - Customer: "I’m dealing with stress and anxiety from my job. I feel really overwhelmed and I dont really know what to do…"
                  Zoey: "Gotcha… I’m so sorry to hear you’re going through this. I noticed you had mentioned feeling stress, anxious, and overwhelmed - is that correct?"
                - Customer: "Yes"
                  Zoey: "Ok! At zant, we offer a wide variety of services and focus areas to help you through times like these. We happen to have providers who are specialists, coaches, and counselors. Would you like a few recommendations?"

        "404":
          description: "scenario not found"
        "500":
          description: "Server Error"
  /ask:
    post:
      summary: "Get an answer by question"
      description: "Retrieve an answer by question"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                question:
                  type: string
                  description: "Question from customer"
                scenarioId:
                  type: integer
                  description: "Optional: for more accurate answer"
                prevAnswer:
                  type: string
                  description: "Optional: for more accurate answer"
              required:
                - question
              example:
                question: "I’m dealing with stress and anxiety from my job."
                scenarioId: 1
                prevAnswer: null
      responses:
        "200":
          description: "An answer object"
          content:
            application/json:
              schema:
                type: object
                properties:
                  answer:
                    type: string
                  scenarioId:
                    type: string

                  prevAnswer:
                    type: string

                example:
                  answer: "I’m dealing with stress and anxiety from my job."
                  scenarioId: 1
                  prevAnswer: null

        "404":
          description: "Answer not found"
